sudo: required
language: python
python:
  #- "2.7"
  - "3.5"

services: docker
# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
  - sudo apt-get update

script:
  - pwd
  - whoami
  - ip addr show
  - docker-compose ps
  - lsb_release -a
  #- docker-compose up -d
  #- docker-compose run web python3 manage.py makemigrations
  #- docker-compose run web python3 manage.py migrate

after_failure:
  - docker-compose down

env:
  - DOCKER_COMPOSE_VERSION = 1.4.2

before_install:
  - docker --version

branches:
  only:
  - travis

before_deploy: "echo 'ready?'"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: igenhub
  on: travis
  install: install
  before_install: before_install
  skip_cleanup: true
  run:
    - pwd
    - ls
    - whoami
    - ip addr show
    - lsb_release -a
    - sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    #- "docker-compose up -d"
    #- "docker-compose run web python3 manage.py makemigrations"
    #- "docker-compose run web python3 manage.py migrate"
    #- "docker-compose ps"

after_deploy: "echo 'Success!'"
