sudo: required
language: python
python:
  #- "2.7"
  - "3.5"

#addons:
#  apt:
#    packages:
#      -sshpass

services: docker
# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
  - docker --version
  - whoami
  - ls
  - sudo apt-get update
  - sudo apt-get install sshpass
  - sshpass -V

script:
  - whoami
  - docker-compose build
  - docker-compose up -d
  - docker-compose run web python3 manage.py makemigrations
  - docker-compose run web python3 manage.py migrate
  - docker-compose ps

after_script:
  - docker-compose down

after_success:
  - export SSHPASS=$DO_PASS

after_failure:
  - docker-compose down

env:
  - DOCKER_COMPOSE_VERSION = 1.4.2

branches:
  only:
  - do

deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -e ssh $HOST@$HOST_IP
  on:
    branch: do
