version: '3'
services:
    db:
        image: postgres
        command: -p 8022
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    web:
        build: .
        volumes:
            - ./igenapp/media:/code/igenapp/media
            - .:/code
        ports:
            - "8021:8021"
        depends_on:
            - db
